algo_master_75_tuples = [
    (2, "Add Two Numbers"),
    (3, "Longest Substring Without Repeating Characters"),
    (4, "Median of Two Sorted Arrays"),
    (7, "Reverse Integer"),
    (11, "Container With Most Water"),
    (15, "3Sum"),
    (19, "Remove Nth Node From End of List"),
    (20, "Valid Parentheses"),
    (23, "Merge k Sorted Lists"),
    (24, "Swap Nodes in Pairs"),
    (25, "Reverse Nodes in k-Group"),
    (33, "Search in Rotated Sorted Array"),
    (34, "Find First and Last Position of Element in Sorted Array"),
    (41, "First Missing Positive"),
    (42, "Trapping Rain Water"),
    (45, "Jump Game II"),
    (46, "Permutations"),
    (48, "Rotate Image"),
    (49, "Group Anagrams"),
    (53, "Maximum Subarray"),
    (54, "Spiral Matrix"),
    (56, "Merge Intervals"),
    (64, "Minimum Path Sum"),
    (75, "Sort Colors"),
    (76, "Minimum Window Substring"),
    (78, "Subsets"),
    (84, "Largest Rectangle in Histogram"),
    (94, "Binary Tree Inorder Traversal"),
    (98, "Validate Binary Search Tree"),
    (102, "Binary Tree Level Order Traversal"),
    (124, "Binary Tree Maximum Path Sum"),
    (127, "Word Ladder"),
    (128, "Longest Consecutive Sequence"),
    (133, "Clone Graph"),
    (139, "Word Break"),
    (142, "Linked List Cycle II"),
    (144, "Binary Tree Preorder Traversal"),
    (145, "Binary Tree Postorder Traversal"),
    (146, "LRU Cache"),
    (149, "Max Points on a Line"),
    (151, "Reverse Words in a String"),
    (155, "Min Stack"),
    (169, "Majority Element"),
    (199, "Binary Tree Right Side View"),
    (200, "Number of Islands"),
    (208, "Implement Trie (Prefix Tree)"),
    (210, "Course Schedule II"),
    (212, "Word Search II"),
    (213, "House Robber II"),
    (230, "Kth Smallest Element in a BST"),
    (236, "Lowest Common Ancestor of a Binary Tree"),
    (238, "Product of Array Except Self"),
    (239, "Sliding Window Maximum"),
    (260, "Single Number III"),
    (295, "Find Median from Data Stream"),
    (297, "Serialize and Deserialize Binary Tree"),
    (300, "Longest Increasing Subsequence"),
    (322, "Coin Change"),
    (329, "Longest Increasing Path in a Matrix"),
    (338, "Counting Bits"),
    (347, "Top K Frequent Elements"),
    (392, "Is Subsequence"),
    (416, "Partition Equal Subset Sum"),
    (435, "Non-overlapping Intervals"),
    (437, "Path Sum III"),
    (438, "Find All Anagrams in a String"),
    (547, "Number of Provinces"),
    (560, "Subarray Sum Equals K"),
    (567, "Permutation in String"),
    (729, "My Calendar I"),
    (785, "Is Graph Bipartite?"),
    (787, "Cheapest Flights Within K Stops"),
    (994, "Rotting Oranges"),
    (1143, "Longest Common Subsequence"),
    (1584, "Min Cost to Connect All Points"),
]
