blind_75_tuples = [
    (1, "Two Sum"),
    (3, "Longest Substring Without Repeating Characters"),
    (5, "Longest Palindromic Substring"),
    (11, "Container With Most Water"),
    (15, "3Sum"),
    (19, "Remove Nth Node From End of List"),
    (20, "Valid Parentheses"),
    (21, "Merge Two Sorted Lists"),
    (23, "Merge k Sorted Lists"),
    (33, "Search in Rotated Sorted Array"),
    (39, "Combination Sum"),
    (48, "Rotate Image"),
    (49, "Group Anagrams"),
    (53, "Maximum Subarray"),
    (54, "Spiral Matrix"),
    (55, "Jump Game"),
    (56, "Merge Intervals"),
    (57, "Insert Interval"),
    (62, "Unique Paths"),
    (70, "Climbing Stairs"),
    (73, "Set Matrix Zeroes"),
    (76, "Minimum Window Substring"),
    (79, "Word Search"),
    (91, "Decode Ways"),
    (98, "Validate Binary Search Tree"),
    (100, "Same Tree"),
    (102, "Binary Tree Level Order Traversal"),
    (104, "Maximum Depth of Binary Tree"),
    (105, "Construct Binary Tree from Preorder and Inorder Traversal"),
    (121, "Best Time to Buy and Sell Stock"),
    (124, "Binary Tree Maximum Path Sum"),
    (125, "Valid Palindrome"),
    (128, "Longest Consecutive Sequence"),
    (133, "Clone Graph"),
    (139, "Word Break"),
    (141, "Linked List Cycle"),
    (143, "Reorder List"),
    (152, "Maximum Product Subarray"),
    (153, "Find Minimum in Rotated Sorted Array"),
    (190, "Reverse Bits"),
    (191, "Number of 1 Bits"),
    (198, "House Robber"),
    (200, "Number of Islands"),
    (206, "Reverse Linked List"),
    (207, "Course Schedule"),
    (208, "Implement Trie (Prefix Tree)"),
    (211, "Design Add and Search Words Data Structure"),
    (212, "Word Search II"),
    (213, "House Robber II"),
    (217, "Contains Duplicate"),
    (226, "Invert Binary Tree"),
    (230, "Kth Smallest Element in a BST"),
    (235, "Lowest Common Ancestor of a Binary Search Tree"),
    (238, "Product of Array Except Self"),
    (242, "Valid Anagram"),
    (252, "Meeting Rooms"),
    (253, "Meeting Rooms II"),
    (261, "Graph Valid Tree"),
    (268, "Missing Number"),
    (269, "Alien Dictionary"),
    (271, "Encode and Decode Strings"),
    (295, "Find Median from Data Stream"),
    (297, "Serialize and Deserialize Binary Tree"),
    (300, "Longest Increasing Subsequence"),
    (322, "Coin Change"),
    (323, "Number of Connected Components in an Undirected Graph"),
    (338, "Counting Bits"),
    (347, "Top K Frequent Elements"),
    (371, "Sum of Two Integers"),
    (417, "Pacific Atlantic Water Flow"),
    (424, "Longest Repeating Character Replacement"),
    (435, "Non-overlapping Intervals"),
    (572, "Subtree of Another Tree"),
    (647, "Palindromic Substrings"),
    (1143, "Longest Common Subsequence"),
]
