repos:
    - repo: local
      hooks:
          - id: update-pre-commit-hooks
            name: update pre-commit hooks
            entry: pre-commit autoupdate
            language: system
            pass_filenames: false
            types: [file]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
            args: ["--maxkb=20000"]
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.28.0
      hooks:
          - name: gitleaks
            id: gitleaks
    - repo: local
      hooks:
          - id: nb-to-py
            name: convert notebooks to python
            entry: make nb-to-py
            language: system
            pass_filenames: false
          - id: lint
            name: lint
            entry: make lint
            language: system
            pass_filenames: false
