[tool.poetry]
name = "leetcode-py-sdk"
version = "0.1.0" # use git tag instead
description = "Modern Python LeetCode practice environment with automated problem generation, beautiful data structure visualizations, and comprehensive testing"
authors = ["Wisaroot Lertthaweedech <l.wisaroot@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/wisarootl/leetcode-py"
repository = "https://github.com/wisarootl/leetcode-py"
keywords = ["leetcode", "algorithms", "data-structures", "interview-prep", "coding-practice"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Education",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
packages = [{include = "leetcode_py"}]
include = ["leetcode_py/cli/resources/**/*"]

[tool.poetry.scripts]
lcpy = "leetcode_py.cli.main:app"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
anytree = "^2.13.0"
black = "^25.1.0"
cookiecutter = "^2.6.0"
graphviz = "^0.21"
json5 = "^0.12.1"
loguru = "^0.7.3"
requests = "^2.32.5"
rich = "^14.1.0"
typer = "^0.19.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.30.1"
isort = "^6.0.1"
jupytext = "^1.16.6"
mypy = "^1.17.1"
nbqa = "^1.9.1"
pre-commit = "^4.3.0"
pytest = "^8.4.1"
pytest-cov = "^7.0.0"
ruff = "^0.13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.requires-plugins]
poetry-plugin-sort = { version = ">=0.2.2", extras = ["plugin"] }

[tool.black]
line-length = 105
target-version = ['py310']
include = '.*\.(py|ipynb)$' # All .py and .ipynb files
extend-exclude = '''
/(
    leetcode_py/cli/resources
)/
'''

[tool.isort]
line_length = 105
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
use_parentheses = true
ensure_newline_before_comments = true
extend_skip_glob = ["leetcode_py/cli/resources/*"]

[tool.ruff]
line-length = 105
target-version = 'py310'
extend-exclude = ["leetcode_py/cli/resources"]

[tool.ruff.lint]
# Core rules - essential for any Python project
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "N", # pep8-naming
]
ignore = ["N806"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.mypy]
files = '**/*.py'
warn_unused_configs = true
ignore_missing_imports = true
disable_error_code = ["return", "no-redef"]
exclude = ["leetcode_py/cli/resources"]

[tool.pytest.ini_options]
testpaths = ["leetcode", "tests"]
python_files = ["tests.py", "test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"
norecursedirs = ["leetcode_py/cli/resources"]

[tool.coverage.run]
omit = ["**/playground.py"]
