name: ci

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    test-reproducibility:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

            - name: Set up Python
              uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
              with:
                  python-version: "3.13"

            - name: Install Poetry
              uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true
                  installer-parallel: true

            - name: Load cached venv
              id: cached-poetry-dependencies
              uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
              with:
                  path: .venv
                  key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

            - name: Install dependencies
              if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
              run: poetry install --no-interaction --no-ansi

            - name: Cache Graphviz
              id: cache-graphviz
              uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
              with:
                  path: /usr/bin/dot
                  key: graphviz-${{ runner.os }}

            - name: Install Graphviz
              if: steps.cache-graphviz.outputs.cache-hit != 'true'
              run: sudo apt-get update && sudo apt-get install -y graphviz

            - name: Delete existing problems
              run: rm -rf leetcode/*/

            - name: Regenerate all problems from templates
              run: make gen-all-problems FORCE=1
              env:
                  # Skip interactive confirmation
                  CI: true

            - name: Run linting to verify reproducibility
              run: make lint
